name: appsimanis
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+29

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # dio: ^4.0.0
  provider: ^5.0.0
  fl_chart: ^0.36.2
  http: ^0.13.3
  google_maps_flutter: ^2.0.6
  shared_preferences: ^2.0.6
  image_picker: ^0.8.0+4
  permission_handler: ^8.1.1
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.9
  geolocator: ^8.1.1
  geocoding: ^2.0.0
  intl: ^0.17.0
  webview_flutter: ^2.0.10
  flutter_svg: ^0.22.0
  carousel_slider: ^4.0.0
  google_fonts: ^2.1.0
  share: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/bgLogin.png
    - assets/images/welcome-removebg-preview.png
    - assets/images/bg1.png
    - assets/images/whatsapp.png
    - assets/images/bghome.png
    - assets/images/pattern1.png
    - assets/images/pattern2.png
    - assets/images/completed-task.png
    - assets/images/web.png
    - assets/images/whatsapp (2).png
    - assets/images/menu_pattern.png
    - assets/images/tenagaKerjaIcon.svg
    - assets/images/UMKMIcon.svg
    - assets/images/map.svg
    - assets/images/smartphone.svg
    - assets/images/padlock.svg
    - assets/images/padlock.png
    - assets/images/message.svg
    - assets/images/message.png
    - assets/images/user.svg
    - assets/images/badge.png
    - assets/images/x-button.png
    - assets/images/server.png
    - assets/images/profilIcon.svg
    - assets/images/profilIcon.png
    - assets/images/UMKMIcon.png
    - assets/images/ProdukIcon.png
    - assets/images/BankIcon.png
    - assets/images/LogoutIcon.png
    - assets/images/LogoWhite.svg
    - assets/images/LogoWhite.png
    - assets/images/slideshow1.jpg
    - assets/images/slideshow2.jpg
    - assets/images/slideshow3.jpg
    - assets/images/permesinan.svg
    - assets/images/pertambangan.svg
    - assets/images/pangan.svg
    - assets/images/kesehatan.svg
    - assets/images/hulu_agro.svg
    - assets/images/ekonomi_kreatif.svg
    - assets/images/website.svg
    - assets/images/cs_icon.svg
    - assets/images/survei.svg
    - assets/images/pie_chart.svg
    - assets/images/fast-food.svg
    - assets/images/share.svg
    - assets/images/AjukanDana.svg
    - assets/images/HubungiKami.svg
    - assets/images/Logo_blue.svg
    - assets/images/cross.svg
    - assets/images/backArrow.svg
    - assets/images/Dana.svg
    - assets/images/filter.svg
    - assets/images/total_ikm.svg
    - assets/images/tenaga_kerja.svg
    - assets/images/ikm_baru.svg
    - assets/images/industri_kecil.svg
    - assets/images/industri_menengah.svg
    - assets/images/industri_besar.svg
    - assets/images/sert_halal.svg
    - assets/images/sert_haki.svg
    - assets/images/sert_sni.svg
    - assets/images/sert_test_report.svg
    - assets/images/formal.svg
    - assets/images/informal.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
